dist: trusty
language: java
git:
  depth: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "thoriumlang"
    token:
      secure: "UclgzeWBm2E/MLewP97M0J1vBvAeUvpc+eCRx9oZuopszRCB9pADf2plrMNbeRTZU0BLYCI3/do+VVkxYQwtrusgvTVzq3E4Xg6M4uclmpjyyMfdbYxONxJLFeiARjy1Zo7GYOG6pylVy7kJmyUnV+BVJWD8bWeyelMMsp0D2Pt89IDLqFZ1nJ5nBGY3byHe97ppKYO/WptJjq/rUZZhknYXNG4KNGTacryuXrTBILjriY8KWwmLLmwopVNyF5tACmn4jgHrc8ZrOlF67gfHsXtDE2jkKleRcudTaYgXYQ5TP6Q8cihv1aRzkNtuDHCcSu9zUFwVKHwMehujuL1zoiyvJFQmTGRUPKae7A0Jn9k+pAfi8BsKnWRyzxFX0i+67vdwyrh3fAhloUtqyoqV8dhxsCM13pV2fbI9BuQFrQ7SGTk/OsrsZTGCW9Yu2tvnybYDg7ZMKfX5+qe+fA2F4u9Jc59FDGxx0MYUyQQ6mzkt8XWKw+8Wo5+68LXBP8s1grpwyYqE+ghHJJUKv5cPQOfRNbWXAOAqmpbbNy+Yqf9uHgY3GPa8e5/a88hM0draeDmq5AxSHJ6PrvD9WXcVEuXIhIFzWnI6LGEyjBWrpgA05oVlb+d0W8JpoeGXH7yP2Kw1UNLLlA+d181urHEn8SL7FEfdt6FRjjx8G1c431M="
script:
  - mvn install
  - mvn sonar:sonar -Dsonar.java.libraries=target
