dist: trusty
language: java
git:
  depth: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "thoriumlang"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn install
  - mvn sonar:sonar -Dsonar.java.libraries=target
